### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by tamimology** [hydazz/docker-duplicati#2]
I am wondering how to include the `.env` file in the backup job?

I cannot see it in the source list at all

**Comment by hydazz** [comment]
I don't know which `.env` file you are referring to, however `.*` are usually hidden. In source data there is a `Show hidden folders` button, clicking this shows hidden folders and files. This just shows hidden files/folders, just ensure that `Hidden files` is not ticked under `exclude`. hidden files do show up in the restore section though.

**Comment by tamimology** [comment]
This was the thing I am missing

All good now mate, thanks
