### ISSUE TITLE
Multi source folders

### ISSUE THREAD

**Issue by tamimology** [hydazz/docker-duplicati#3]
It would be more convenient to be able to bind more than 1 source folder, in which each folder is located under a different root folder

i.e. 
```
    volumes:
      - folder1/subfolder:/source/folder1
      - folder2/subloders:/source/folder2
```
     
or something similar

**Comment by hydazz** [comment]
There is nothing limiting you from doing this?

**Comment by tamimology** [comment]
I tried and didn't work
It gave me error mapping more than 1 folder to the source

That is why I opened the issue

**Comment by hydazz** [comment]
```
    volumes:
      - folder1/subfolder:/source/folder1
      - folder2/subloders:/source/folder2
```
should work, however you are not limited to the /source folder, you can mount wherever.

mounting a folder inside of a mount, eg
```
    volumes:
      - folder1/subfolder:/source/
      - folder2/subloders:/source/folder2
```
would not work.

can you provide your actual compose volumes?

**Comment by tamimology** [comment]
I can confirm it is working now

It is confusing as it adds the new mounted fokders with the old ones and muxes them up. I had to delete the config folder and recreate everything from scratch to reset the volumes
